---
#name:
surname: Rayna M. Harris, PhD
position: "Science, Education, Community Engagement"
#address:  
#phone:  
www: www.raynaharris.com
email: "rayna.harris@gmail.com"
#twitter: raynamharris
#github: raynamharris
#linkedin: raynamharris
date: "`r format(Sys.time(), '%B %Y')`"
output: vitae::moderncv
fontsize: 11pt
headcolor: "000000"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
library(rorcid)
library(tibble)
library(scholar)
library(tidyverse)
library(pkgsearch)
```




```{r example, include = FALSE}

# Marie Curie Nobel Prizes

tribble(
  ~Year, ~Type, ~Desc,
  1903, "Physics", "Awarded for her work on radioactivity with Pierre Curie and Henri Becquerel",
  1911, "Chemistry", "Awarded for the discovery of radium and polonium"
) %>% 
  vitae::brief_entries(
    Type,
    Year, 
    Desc
  )
```



# Education


```{r education-orcid }
orcid_data <- do.call("rbind",
  rorcid::orcid_educations("0000-0002-7943-5650")$`0000-0002-7943-5650`$`affiliation-group`$summaries
)

orcid_data %>%
  brief_entries(
    what = `education-summary.role-title`,
    when = glue::glue("{`education-summary.start-date.year.value`} - {`education-summary.end-date.year.value`}"),
    with = `education-summary.organization.name`
  )
```
# Certifications

```{r certification}

tribble(
  ~Year, ~Type, ~Desc, 
  "2024", "200-hour Hatha Yoga Teacher Training", "Palisades Yoga, Olympic Valley, CA"
) %>% 
  vitae::brief_entries(
    Type,
    Year, 
    Desc
  )

```

# Experience

```{r experience, include = TRUE}

tribble(
  ~Year, ~Type, ~Desc,
  #"2023 - 2024", "Mountain Host Lead", "Palisades Tahoe",
  "2023 - 2024", "Adjunct Faculty", "Lake Tahoe Community College",
  "2021 - 2023", "Postdoctoral Scholar", " University of California, Davis",
  "2020 - 2022", "Parking Supervisor", "Alpine Meadows Ski Resort ",
 # "2020 - 2021", "Nursery Supervisor", "Rock & Rose Nursery & Landscaping ",
  "2018 - 2020", "Postdoctoral Scholar", " University of California, Davis",
  "2010 - 2012", "Laboratory Manager", "The University of Texas at Austin",
  "2007 - 2010", "Teaching Specialist", "The University of Texas at Austin",
) %>% 
  vitae::brief_entries(
    Type,
    Year, 
    Desc
  ) 

```


# Honors and Awards

```{r honors, include = TRUE}

tribble(
  ~Year, ~Type, ~Desc,
  "2019", "AAAS Community Engagement Fellowship", " ",
  #"2019", "rstudio::conf 2019 Diversity Scholarship", " ",
 # "2017", "Outstanding Graduate Student Academic Employee Award", "  ",
 # "2016, 17", "University Graduate Continuing Fellowship", " ",
  "2014, 15, 16", "Academic Enrichment Fund Award", " ",
 # "2013, 11, 15", "Honorable mention, National Science Foundation Graduate Research Fellowship", " ",
) %>% 
  vitae::brief_entries(
    Type,
    Year, 
    Desc
  )

```

# Teaching Experience

```{r teaching}
tribble(
  ~ with, ~ what, ~ when, 
  "Principles of Biology III Lab (BIO 103)", "Lake Tahoe Community College", "Spring 2024",
  "Yoga Instructor", "Courage Project", "2023 - 2024",
  "Organic Chemistry III Lab (CHM 223L)", "Lake Tahoe Community College", "Spring 2023", 
  "Cell and Molecular Biology (BIO 110)", "Lake Tahoe Community College", "Spring 2023", 
  "Principles of Biology III Lecture (BIO 103)", "Lake Tahoe Community College", "Winter 2023", 
  "Introduction to R", "University of California, Davis", "2022", 
  "Introduction to Cloud Computing", "University of California, Davis", "2022",
  "Introduction to UNIX for Cloud Computing", "University of California, Davis", "2022",
  "Instructor Training", "The Carpentries", "2016 - 2019",
  "Biostatistics (SDS 328M)", "The University of Texas at Austin", "2017", 
  "Problems in Modern Biology (BIO 301E)", "The University of Texas at Austin", "2013", 
  "Organic Chemistory Laboratory (CH 210C)", "The University of Texas at Austin",  "2007 - 2010",
  "Introduction to Spanish", "Futura Language Professionals",  "2008 - 2009",
) %>% 
  brief_entries(with, when, what)
```




# Selected Publications

_Available at <https://scholar.google.com/citations?user=_bVy9pMAAAAJ&hl=en>_ \

```{r publications}

pubs <- scholar::get_publications("_bVy9pMAAAAJ&hl")  %>% 
  drop_na(year) %>%
  arrange(desc(year)) %>%
  filter(!str_detect(author, "^SCP")) %>%
  filter(!str_detect(author, "^AK")) %>%
  filter(!str_detect(author, "^EK")) %>%
  filter(!str_detect(author, "^AL")) %>%
  filter(!str_detect(author, "^AS")) %>%
  filter(!str_detect(author, "^AJ")) %>%
  filter(!str_detect(author, "^C")) %>%
  filter(!str_detect(author, "^KA")) %>%
  filter(!str_detect(author, "Dijkstra")) %>%
  filter(!str_detect(author, "Barata")) %>%
  filter(!str_detect(author, "Oldfield")) %>%
  filter(!grepl("Columba|long-term|findability|Single-Neuron|Isolating", title)) %>%
  mutate(author = gsub("\\...", "et al.", author)) %>%
  vitae::brief_entries(
    with = paste(journal, number, sep = " "),
    when = year,
    what = paste(author, title, sep = ", ")
  )
pubs

```


```{r presies, include = F}

# Selected Presentations 

# _Available at <https://speakerdeck.com/raynamharris>._  \


read.table("speakerdeck.txt", sep = ";", header = 1) %>%
  vitae::brief_entries(
    with = Where,
    when = Year,
    what = Title
  )

```

# Service

```{r service, include = TRUE}

tribble(
  ~Year, ~Type, ~Desc,
  "2023 - 2024", "Yoga Instructor ", "Courage Project",
  #"2023", "Ambassador ", "5 Gyres",
  #"2019", "Coordinator", "I Can Science, a National Geographic Video Series",
  "2018 - 2019", "Spanish Translator", "The Carpentries",
  "2017 - 2018", "Secretary", "Software Carpentry Steering Committee",
  "2016 - 2017", "Poster Judge", "College of Natural Science Undergraduate Research Forum",
  "2012 - 2017", "Coordinator", "Annual Big Data in Biology Symposium",
  "2014 - 2016", "Coordinator", "Summer School for Big Data in Biology",
  "2014", "Coordinator", "Transdisciplinary Graduate Student Luncheon",
  "2009", "Spanish Translator", "INBio Park, Costa Rica",
  " ", "Peer-reviewer", "AAS  Open  Research; Behavioral Ecology; Genes, Genomes & Genetics; Genes, Brains & Behavior; Journal of Experimental Zoology Part A; Nature; Physiology & Behavior; Proceedings of the Royal Society B; rOpenSci",) %>% 
  vitae::brief_entries(
    Type,
    Year, 
    Desc
  )

```
